---
title: "Kulturförderung der Stadt Uster"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: journal
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)

library(tidyverse)
library(lubridate)

library(tm)
library(wordcloud)
library(RColorBrewer)
library(RCurl)


#Datenimport und -aufbereitung
data <- read.csv("https://raw.githubusercontent.com/GesellschaftStadtUster/kultur_foerderbeitrage/main/daten_kulturfoerderung_uster.csv")
data <- as.data.frame(data)
alledata <- arrange(data, desc(Datum.Entscheid))
alledata$Datum.Entscheid <-format(as.Date(alledata$Datum.Entscheid), format = "%d.%m.%Y")


data2018 <- data %>% filter(Datum.Entscheid >= as.Date("2018-01-01") & Datum.Entscheid <= as.Date("2018-12-31"))
summe2018 <- sum(data2018$Förderbeitrag.in.CHF)

data2019 <- data %>% filter(Datum.Entscheid >= as.Date("2019-01-01") & Datum.Entscheid <= as.Date("2019-12-31"))
summe2019 <- sum(data2019$Förderbeitrag.in.CHF)

data2020 <- data %>% filter(Datum.Entscheid >= as.Date("2020-01-01") & Datum.Entscheid <= as.Date("2020-12-31"))
summe2020 <- sum(data2020$Förderbeitrag.in.CHF)

summe <- c(summe2018,summe2019,summe2020)

```


Row
-----------------------------------------------------------------------

### Kulturförderbeiträge

```{r}

barplot(summe/1000, ylab="Gesamtbeitrag pro Jahr in 1000 CHF", names.arg=c(2018,2019,2020))

```

### Wortwolke der Projekte

```{r}
#Wortwolke
filterbegriffe <- c("uster","ein","der","ein","von","für","eine","leistungskontrakt","mit","und")
doc <- Corpus(VectorSource(data$Projekt))
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
doc <- tm_map(doc, toSpace, "/")
doc <- tm_map(doc, toSpace, "\\|")

doc <- tm_map(doc, content_transformer(tolower))
doc <- tm_map(doc, removeNumbers)
doc <- tm_map(doc, removeWords, stopwords("german"))
doc <- tm_map(doc, removeWords, filterbegriffe) 
#doc <- tm_map(doc, removePunctuation)
doc <- tm_map(doc, toSpace, ":")
doc <- tm_map(doc, toSpace, "«")
doc <- tm_map(doc, toSpace, ",")
doc <- tm_map(doc, stripWhitespace)
#doc <- tm_map(doc, stemDocument)
tdm <- TermDocumentMatrix(doc)
m <- as.matrix(tdm)
v <- sort(rowSums(m),decreasing=TRUE)
df <- data.frame(word = names(v),freq=v)
set.seed(1001)
wordcloud(words = df$word, freq = df$freq, min.freq = 2, scale=c(3,0.5),
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))       
text(x=0.90, y=0, date())
```

### Chart C

```{r}

```

Row
-----------------------------------------------------------------------

### Fördergesuche

```{r}
kable(alledata)
```
